### ISSUE TITLE
Allow config to be passed in individually

### ISSUE THREAD

**Issue by mook-as** [SUSE/eirini-loggregator-bridge#13]
[Currently], the config must be passed in via `--config` as a JSON/YAML/whatever file.  We exit immediately if `--config` is not specified.  I'd like to change this so that it would be _possible_ (but probably optional) to pass in the [individual options] in as separate things (from the environment, because `viper` supports that), to make it easier to support deploying this as a helm chart (where writing out a config file would necessitate having an init container).

I'm happy to do the work; I'm just raising an issue first to gauge interest.  Please let me know if this seems sensible.

I'd expect `--config` to continue to be supported.

[Currently]: https://github.com/SUSE/eirini-loggregator-bridge/blob/8c8504b7c3a5efaee58b0f4d9b6bd65de828639d/cmd/root.go#L60-L73
[individual options]: https://github.com/SUSE/eirini-loggregator-bridge/blob/8c8504b7c3a5efaee58b0f4d9b6bd65de828639d/config/config.go#L12-L16

**Comment by mudler** [comment]
That sounds good! I've sketched up https://github.com/SUSE/eirini-loggregator-bridge/pull/14 for an implementation example
